### ISSUE TITLE
Able to pass props to buttons

### ISSUE THREAD

**Issue by WillowP** [mikelpmc/react-multiline-clamping#17]
Hi! This library is great!

I'm using this with [Bulma](https://bulma.io), and I'd love to be able to pass down some `classNames` to add to the `Show More` and `Show Less` buttons.

I was thinking the best way to do this would be to add another prop to `Clamp` like:

```js
buttonProps = {
  showMore: {},
  showLess: {},
}
```

and then spread the props in like:

```js
            {showMore && !isExpanded && (
                <button
                    type="button"
                    onClick={() => handleToggleShowMore(true)}
                    {...buttonProps.showMore}
                >
                    {texts.showMore}
                </button>
            )}

            {isExpanded && (
                <button
                    type="button"
                    onClick={() => handleToggleShowMore(false)}
                    {...buttonProps.showLess}
                >
                    {texts.showLess}
                </button>
            )}
```

If this sounds good, I'd love to contribute this change. Let me know :)

Thanks.

**Comment by mikelpmc** [comment]
Hey Willow!

Love to hear that you found this little library useful :)

I was thinking on what you said and your solution looks great for what you are trying to archieve.
However I think we could maybe invert the show more/less buttons render responsability to the library consumer and that would be much more flexible, allowing more use cases not only passing custom props, classes etc but even entire custom components or maybe another elements and not only buttons.

There was another issue opened that asked about passing another elements instead of buttons and I think we could use this approach to cover both cases.

Take a look to this PR and let me know what you think and if you think it suites your use case :)

https://github.com/mikelpmc/react-multiline-clamping/pull/19

And thanks again for your kind words and interest on contributing.

**Comment by WillowP** [comment]
Hey, this looks fantastic! Looking forward to trying it out :)

I'll close this issue, since it's much better handled by the PR you referenced.

Thanks again for the great tool.
